# Generated by Django 3.2.25 on 2024-04-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0001_initial'),
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_projet', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('client_concerne', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.client')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'contrat', 'verbose_name_plural': 'contrats'},
        ),
        migrations.AlterField(
            model_name='consultant',
            name='clients',
            field=models.ManyToManyField(to='gestion_clients.Client'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client_concerne',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.client'),
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='consultant',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant'),
        ),
    ]
