# Generated by Django 3.2.20 on 2024-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_auto_20240429_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='tjm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
