# Generated by Django 3.2.20 on 2024-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventconge',
            name='duration',
        ),
        migrations.AddField(
            model_name='eventconge',
            name='type',
            field=models.CharField(choices=[('congé payé', 'Congé payé'), ('congé non payé', 'Congé non payé'), ('RTT', 'RTT')], default='congé payé', max_length=50),
        ),
    ]
