# Generated by Django 3.2.20 on 2024-05-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0002_auto_20240522_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_table',
        ),
        migrations.DeleteModel(
            name='EventTable',
        ),
    ]
