# Generated by Django 3.2.20 on 2024-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='event_table_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tjm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
