# Generated by Django 3.2.20 on 2024-05-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0005_auto_20240524_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cra.events')),
            ],
        ),
    ]
