# Generated by Django 3.2.20 on 2024-05-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_consultant_tjm'),
        ('cra', '0008_events_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtable',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultant.consultant'),
        ),
    ]
